### ISSUE TITLE
formplayer service build error

### ISSUE THREAD

**Issue by DeckOfPandas** [WDDCP/commcare-wddcp#21]
(Combining previous Issues #8 and #9 )

Saving/previewing/running applications apparently requires formplayer: see threads [here](https://groups.google.com/forum/#!searchin/commcare-developers/Unable$20to$20validate$20the$20forms$20due$20to$20a$20server$20error.%7Csort:relevance/commcare-developers/qD8BC8jKjDw/-WxlBgmJBgAJ) and [here](https://groups.google.com/forum/#!searchin/commcare-developers/Unable$20to$20validate$20the$20forms$20due$20to$20a$20server$20error.%7Csort:relevance/commcare-developers/vpABXpTlb5I/-PEvu9R4BQAJ)

The formplayer repo is https://github.com/dimagi/formplayer , and I am having trouble building this.

THE FOLLOWING IS ALL OUT OF DATE NOW
What I did, in order:
* Clean checkout of commcare-wddcp, checked out branch :wddcp
* Added formplayer as a submodule:
`[submodule "corehq/apps/formplayer"]
	path = corehq/apps/formplayer
	url = https://github.com/dimagi/formplayer`
* Updated submodules to grab the formplayer code: `git submodule update --init --recursive`
* Followed steps in https://github.com/dimagi/formplayer README:
  * `cp config/application.properties.example config/application.properties`
    * Set commcarehq.host port (I use 5555) in this file
  * BUT I don't know how to create the formplayer db as it asks: `createdb formplayer -U commcarehq -h localhost`
    * I suspect I shouldn't do this on my local machine, so is this supposed to be done inside the docker box?
    * So pausing that step for now...
* Followed steps in our README: https://github.com/WDDCP/commcare-wddcp/blob/wddcp/README.md
  * Stopped without final `runserver` step
* Inside docker box, inside corehq/apps/formplayer:
  * Trying the `createdb` step from the formplayer README gives
`root@9a133b004e9e:/mnt/commcare-hq/corehq/apps/formplayer# createdb formplayer -U commcarehq -h localhost`
`bash: createdb: command not found`
   * So continuing to not do that step
   * Building as per formplayer docs `./gradlew build; java -jar build/libs/formplayer.jar` gives $pastebinlink (pastebin is dead atm...will update when it is not); some failed tests, and overall BUILD FAILED, and Spring booted but couldn't run the container
   * BUT 'something' was running, so I ran the `runserver` script (inside the vagrant box not docker box), and unsurprisingly still get the error about the 'server error', screenshot in picture below:

![screen shot 2017-07-15 at 09 51 11](https://user-images.githubusercontent.com/2399432/28238062-78a5123a-6943-11e7-86be-d542f9caa054.png)

**Comment by DeckOfPandas** [comment]
@doismellburning

**Comment by DeckOfPandas** [comment]
@pacharanero

**Comment by lamby** [comment]
> createdb formplayer -U commcarehq -h localhost

Untested yet, but ``createdb`` is a [PostgreSQL](https://www.postgresql.org/) subcommand. You want something like:

```
sudo -u postgres createdb formplayer -U commcarehq -h localhost
```
or

```
sudo -u postgresql createdb formplayer -U commcarehq -h localhost
```


(The ``-h localhost`` might not be required and may not even work.)

**Comment by lamby** [comment]
Having a quick poke at this. One thing to immediately notice is that even when viewing a project (not previewing etc.) I see:

```
OPTIONS http://localhost:8080/delete_application_dbs net::ERR_CONNECTION_REFUSED
                         ^^^^
```

Note, that this is ``:8080`` (``settings.FORMPLAYER_URL`` in settings.py line 612), not ``:8000`` ie. what Django "thinks" it is) nor the URL I happen to be using (right now, ``:2345``).

This implies that, wherever we end up running Formplayer, we will need to be able to get requests to it, perhaps opening more ports on Vagrant and then additionally into another docker image.

**Comment by lamby** [comment]
@DeckOfPandas 

> gives $pastebinlink (pastebin is dead atm...will update when it is not); 

Is it back up? :)

**Comment by DeckOfPandas** [comment]
What if you run the webserver on 8080 rather than 2345? When I was first getting to grips with vagrant most tutorials forwarded 8080 on the vagrant to 8000 on the host, so maybe that code is lazy and vestigial....?

**Comment by lamby** [comment]
> What if you run the webserver on 8080 rather than 2345

That would not work as the webserver is not going to proxy the request to the formplayer server. One way of demonstrating this is simply to go to, for example, ``http://localhost:2345/delete_application_dbs`` - it hits *Django*, not anything else. :)

**Comment by lamby** [comment]
> it hits Django, not anything else

As in, it hits Django "succesfully" with a 404 and doesn't *fail* to hit anything else. :)

**Comment by lamby** [comment]
Just playing inside a fresh Debian unstable chroot I can get it to build after applying:

```
-- libs/commcare/build.gradle.orig	2017-09-18 11:02:36.140019019 +0100
+++ libs/commcare/build.gradle	2017-09-18 11:02:45.984085278 +0100
@@ -241,8 +241,6 @@
     }
 }
 
-check.dependsOn(jenkinsTest)
-
 jmh {
     duplicateClassesStrategy = 'warn'
     fork = 2
```

(It then fails with some kind of connection error, probably missing postgresql etc. but haven't looked in more detail yet)

**Comment by lamby** [comment]
Yep, postgres: https://gist.github.com/lamby/aef5a8cd6dc1c016a260fd906105a8d7/raw

**Comment by lamby** [comment]
Here's today's progress. Alas I still don't have it working.. urgh.

* I'm basing this on https://github.com/dimagi/formplayer/commit/544683b6275d84b8f60c838bcf3bb33c38312723

* formplayer does neither builds nor runs on Java 9 (or at least the OpenJDK 9 I have here). Probably not a problem as Xenial — the image we are using elsewhere — is unlikely to ship with this by default.

* ``sudo apt install --yes openjdk-8-jdk``

* ``cp config/application.example.properties config/application.properties``

* Create a PostgreSQL user:

```
sudo -u postgres createuser commcarehq -SDRP
Enter password for new role: <commcarehq>
Enter it again:  <commcarehq>
```
* Create a ``formplayer`` db under the ``commcarehq`` user: ``$ sudo -u postgres createdb -E UTF-8 -O commcarehq formplayer``

* Build with ``./gradlew``.

* Check the management server and server is actually up and accepting connections before going any further:

```
$ curl http://127.0.0.1:8081/
{"timestamp":1506094934105,"status":404,"error":"Not Found","message":"/","path":"/"}

$ curl http://127.0.0.1:8080 
{"error":"Invalid session id"}
```

* ``settings.BASE_ADDRESS`` in commcare *must* match what you are accessing the site via in the browser. ie. you cannot have a ``config.vm.network "forwarded_port", guest: 8000, host: X`` in your ``Vagrantfile`` where ``X`` does not match the port mentioned in ``settings.BASE_ADDRESS`` in your localsettings. This is due to the commcare Javascript sending an ``Access-Control-Allow-Origin`` header of ``settings.BASE_ADDRESS`` which violates `CORS <https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS>`__ restrictions in modern browsers.

* Be especially aware that changing the port of  ``BASE_ADDRESS`` in ``localsettings.py`` **does not actually work**. I've yet to discover why but even after re-running the docker initialisation, whilst adding debugging statements to ``settings.py`` will happily print the modified value, if you then query ``settings.BASE_ADDRESS`` at runtime at all (eg. just dump some ``print`` in an already-existing middleware.) it *prints an empty string* (whut).

* Therefore I currently suggest setting ``guest: 8000, host: 8000``. This avoids having to change ``commcarehq.host=http://localhost:8000`` to, say, ``commcarehq.host=http://localhost:2345`` too.

----

However despite all this, I'm now getting:

```
POST http://localhost:8080/delete_application_dbs 404 ()
```
Googling "delete_application_dbs" just gets, well, this issue. You might get a CORS error as the 404 does not include the headers, but the real issue is the 404 AIUI.

**Comment by lamby** [comment]
(Some more self-notes on this.)

* ``delete_application_dbs`` does exist in formplayer, eg. ``src/main/java/application/UtilController.java``.

* The ``POST http://localhost:8080/delete_application_dbs 404 ()`` seems misleading - the POST is actually 403ing when you turn on (or look at) the formplayer logging. (See the final parts of ``application.properties``)

Full log of a failing request here:

https://gist.githubusercontent.com/lamby/e107a5385e96aa3b0a34adff22fccc76/raw

* It posts back to Django (``Created POST request for "http://localhost:8000/hq/admin/session_details/") presumably to check auth details.

* Ah. the HTTP 403 is Django 403ing:

```
2017-09-24 19:54:02.448 DEBUG 28362 --- [nio-8080-exec-4] org.apache.http.wire                     : http-outgoing-2 << "HTTP/1.0 403 Forbidden[\r][\n]"
2017-09-24 19:54:02.448 DEBUG 28362 --- [nio-8080-exec-4] org.apache.http.wire                     : http-outgoing-2 << "Date: Sun, 24 Sep 2017 18:54:00 GMT[\r][\n]"
2017-09-24 19:54:02.448 DEBUG 28362 --- [nio-8080-exec-4] org.apache.http.wire                     : http-outgoing-2 << "Server: WSGIServer/0.1 Python/2.7.13[\r][\n]"
                                                                                                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

* ``http://localhost:8000/hq/admin/session_details/`` maps to ``corehq/apps/reports/dispatcher.py → AdminReportDispatcher``. This is *really* hidden due to:

```
 73     url(r'^top_five_projects_by_country/$', top_five_projects_by_country, name='top_five_projects_by_country'),
 74     url(r'^web_user_data', WebUserDataView.as_view(), name=WebUserDataView.urlname),
 75     AdminReportDispatcher.url_pattern(),
```

.. which is ingeniously sneaky.

And now I am getting a genuine 404 on the Django side:

```
2017-09-24 20:11:35.584 DEBUG 28362 --- [nio-8080-exec-9] org.apache.http.wire                     : http-outgoing-4 >> "Accept-Encoding: gzip,deflate[\r][\n]"
2017-09-24 20:11:35.584 DEBUG 28362 --- [nio-8080-exec-9] org.apache.http.wire                     : http-outgoing-4 >> "[\r][\n]"
2017-09-24 20:11:35.584 DEBUG 28362 --- [nio-8080-exec-9] org.apache.http.wire                     : http-outgoing-4 >> "{"sessionId":"dt8vxy2ik1rfjqr56y78y84fn2rfzn02","domain":"test-project"}"
2017-09-24 20:11:35.725 DEBUG 28362 --- [nio-8080-exec-9] org.apache.http.wire                     : http-outgoing-4 << "HTTP/1.0 404 Not Found[\r][\n]"
```

* This suggests to me that there might be some underlying version mismatch here :/

**Comment by lamby** [comment]
* ![](https://i.imgur.com/rF5gTKy.jpg) hehe

* Tried adding a ghetto view, at least to see wtf is going on with this random ``/session_details/`` request from formplayer: https://gist.github.com/lamby/3d2779fe67770d83939bba33aa670c04/raw

* This results in a ``NullPointerException``: https://gist.github.com/lamby/8d06eb6ed340eb32c37854a812d9e431/raw

* Even when I do something like

```
-    return JsonResponse()
+    return JsonResponse({'domains': []})
```

This results in noting

Anyway, I'm *really* floundering now and not being very effective. I really think we are missing Something Big or important here. Yeah...

**Comment by DeckOfPandas** [comment]
Things I have found that might be interesting:

* https://groups.google.com/forum/#!topic/commcare-developers/SAtGSgWN2LA

```
Commcare build 2.0 is listed as unstable so I updated the build to the latest version 2.34.
do I have to do something to the formplayer to align these?
```
* https://groups.google.com/forum/#!searchin/commcare-developers/formplayer|sort:relevance/commcare-developers/puK__p5qUmo/T98-nUVgBgAJ

```
Did you do the first step, which is "$ git submodule update --init --recursive"?
It looks the error is that gradle can't find commcare, which is a submodule of the formplayer project
```

```
I have gotten past this by doing the following.

I cloned the formplayer repo into the commcarehq home directory.
then I ran the git submodule update --init --recursive" script from the formplayer directory.
this allowed for a successful build from the same directory.  

I reran my migration, ptop_all and topics to ensure that all was updated 
```

This same person also seems to have a running service called formserver which I /definitely/ don't have...
```
not sure what needs what but im setting up the following

nginx 2g
kafka 4g
postgres 4g
couch 2g
elasticsearch 6g
formserver 4g 
```

**Comment by DeckOfPandas** [comment]
@lamby As I said earlier, I'm going through every step painstakingly...

Did you ever do this? 
`Finally, turn on the "Use the new formplayer frontend" feature flag on your CommCareHQ domain`

**Comment by lamby** [comment]
@DeckOfPandas I did not. Where is that written? :)  Not quite sure what they mean by "domain" there.

**Comment by lamby** [comment]
^ And, just to be sure, the "can't build errors" wrt gradle etc. quoted above aren't where I got stuck as, well, I *can* build it! \*g*

**Comment by DeckOfPandas** [comment]
Sure -- I meant what if the 'big thing we were missing' was turning this flag on in the frontend....?

That line is from:
https://github.com/dimagi/formplayer
(the last line above the bold **Keeping your application.properties up to date**)

**Comment by DeckOfPandas** [comment]
Just added a line to my first post in this thread saying it's out of date -- thanks :)

**Comment by lamby** [comment]
nodnod :)  Hope it's this easy!

**Comment by lamby** [comment]
Quickly grepping, might be related to ``./corehq/apps/domain_migration_flags`` or ``FORMPLAYER_USE_LIVEQUERY``...

**Comment by DeckOfPandas** [comment]
@lamby Sorry to bug you with this, as I know context switching to things like this is hard, but @TheTincho would benefit from some clarification that I can't really give.

Quick extract from an email conversation:
`T: The thing I am missing is how to actually start the service. From your
notes it seems it starts when you run "gradlew build"?`

`Me: To be perfectly honest with you I don't know. /Something/ definitely runs when I do that. Dimagi's notes say "...When building on Linux it is sometimes necessary to run: $ gradle wrapper..." `

`T: java -jar build/libs/formplayer.jar
The problem is that it does not work when I do that, so I was trying
other ways to start it. I managed to start something, but does not listen on any network port.`

**Comment by lamby** [comment]
@DeckOfPandas @TheTincho 

> > it does not work when I do that

I did not need to touch gradle to get something running and listening; as mentioned, ``java -jar ./build/libs/formplayer.jar`` worked for me and listened on two ports, one "real" and one management. Do see my notes regarding turning on debug-level logging; perhaps that will help enlighten. One might need PostgreSQL to be setup, but I would have seen that error in a log *first* before simply setting it up rather than simply copy-pasting from the docs. Failing that, you might need to elaborate on "it does not work" in terms of output, etc. etc.

Hope that helps.

**Comment by NightTsarina** [comment]
Hey. The thing is, I am going through the procedures, trying to avoid all the automagic scripts, to have a better understanding of what happens.

Something has gone different because of that, and my jar seems to lack a Main-Class attribute, and possibly a classpath. So I had to manually specify classpath and class to execute, and still I don't see any useful output, nor a socket being open.

This is the only visible output:
```
$ export CLASSPATH=...
$ java application.Application
log4j:WARN No appenders could be found for logger (org.springframework.core.env.StandardEnvironment).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::        (v1.4.3.RELEASE)
```

So if running java -jar worked for you, I need to debug that. Would you be able to share that jar so I can inspect it?

**Comment by lamby** [comment]
@TheTincho @DeckOfPandas 

> This is the only visible output:

Is this with logging in ``configuration.properties`` as mentioned? Alternatively, the output does suggest you don't have the logging framework installed \*g*

> ``$ java application.Application``

Don't quite get why you are trying this new (!) route when you mention you are trying to follow the procedures; I mean, the docs mention ``java -jar``.

>  Would you be able to share that jar so I can inspect it?

https://people.debian.org/~lamby/formplayer.jar (61MiB)

**Comment by NightTsarina** [comment]
Yes, the configuration is set, but it does not seem to apply. Also, the config is for the standard logger, but this is complaining about log4j stuff, which I haven't found a way to configure.

And I tried the java -jar route, but the jar I have built does not have the information to start an application, that's why I am asking yours :)

**Comment by lamby** [comment]
@TheTincho @DeckOfPandas 

> the jar I have built does not have the information to start an application

My gut tells me that trying to proceed and without the ``.jar`` having an entry point (!) means something more fundamental is broken, so delving deeper into ways of hacking around that is not going to be very fruitful or productive.

Please pastebin your entire build logs and what happens when you try ``java -jar``. I am not psychic alas :)

**Comment by NightTsarina** [comment]
I think the problem must be some difference with gradle (as I was using the system version and xenial has an old one), as it did not include all the dependencies nor a proper MANIFEST.MT. In any case, I was not asking for help debugging that, I don't really care about the building process :-)

**Comment by NightTsarina** [comment]
I keep having weird issues with the main application. First some failures due to using overlay instead of aufs (not supported in my kernel). Once I fixed that, now I get this error, which I am being unable to fix so far:

```
Traceback (most recent call last):
  File "./manage.py", line 118, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 341, in execute
    django.setup()
  File "/usr/local/lib/python2.7/site-packages/django/__init__.py", line 22, in setup
    configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
  File "/usr/local/lib/python2.7/site-packages/django/utils/log.py", line 75, in configure_logging
    logging_config_func(logging_settings)
  File "/usr/local/lib/python2.7/logging/config.py", line 794, in dictConfig
    dictConfigClass(config).configure()
  File "/usr/local/lib/python2.7/logging/config.py", line 559, in configure
    'filter %r: %s' % (name, e))
ValueError: Unable to configure filter 'hqcontext': Cannot resolve 'corehq.util.log.HQRequestFilter': No module named dimagi.utils.chunked
```

A google search find one post in the user group, which got very unhelpful replies. And the amount of layering makes it way harder to debug. I am tempted to try doing this without docker, but that will probably take a lot of time..

Any ideas?

**Comment by lamby** [comment]
> Cannot resolve 'corehq.util.log.HQRequestFilter':

No idea, but are you sure you have all the submodules available? I believe it pulls in some stuff from elsewhere..

**Comment by NightTsarina** [comment]
Yes, although I had to hack some stuff to be able to sync them, because some of the commit hashes in the wddcp repo were not reachable any more..

**Comment by NightTsarina** [comment]
Well, this is funny.. After finally managing to make commcare work (see my notes in #33), it seems the formplayer is working

**Comment by NightTsarina** [comment]
Now I have moved my deployment to a bigger server, and all the weird artifacts disappeared: it seems some things were failing for being slow or lacking memory.

To solve the CORS issues, I configured an apache reverse-proxying both commcare-hq and the formplayer, that seems to work OK.

Now I am at the stage of seeing the 403 errors when talking with the formplayer.

**Comment by NightTsarina** [comment]
I was receiving some elastic search errors when trying to log in from the simulated app. So I nuked and then rebuilt the indexes:

./manage.py ptop_es_manage --code_red
./manage.py ptop_preindex

I am not sure why this was needed..

**Comment by lamby** [comment]
>  (see my notes in #33), it seems the formplayer is working

Just FYI I — and I think @DeckOfPandas too? — had interpreted this as the formplayer 403 errors until I saw:

> Now I am at the stage of seeing the 403 errors when talking with the formplayer.

:)

**Comment by NightTsarina** [comment]
Also got a SQL error when trying to list web users.. I tried to run migrations again, but still I get django errors...

`relation "users_domainrequest" does not exist`


https://groups.google.com/forum/#!topic/commcare-developers/VFCi6wnsnKs

**Comment by NightTsarina** [comment]
Oh, actually you had to create the migrations before running them.. Not in the docs:

```
$ ./manage.py makemigrations
$ ./manage.py migrate
```

**Comment by DeckOfPandas** [comment]
I think that's in my notes (?)

**Comment by NightTsarina** [comment]
About the error being presented as a 404, I think the issue is that the error handler for the Spring framework is missing. The underlying error seems to be a 403 (Forbidden) when performing an internal POST request to the SessionDetailsUrl, which is in turn triggered by the formplayer operations.

**Comment by lamby** [comment]
> The underlying error seems to be a 403 (Forbidden) when performing an internal POST request to the SessionDetailsUrl

Mmm, you've seen my notes on this specific thing, right? :)

**Comment by NightTsarina** [comment]
I thought I had found the issue, but it is not THE one. Still, it seems you need to set `commcarehq.formplayerAuthKey` to the same value as `SECRET_KEY`

**Comment by NightTsarina** [comment]
Looking at the problematic admin/session_details POST, I don't get a 404, but a 403 there. The debug output shows that django is complaining of "Cookies Required for CSRF"

**Comment by NightTsarina** [comment]
Funny thing, if I try to disable the CSRF middleware, instead of a 403, I *do* get a 404...

**Comment by NightTsarina** [comment]
Also, I can' t find where the session_details endpoint is defined. The one that Chris pointed out does not seem to me to be the one.. but I can' t find anything anywhere pointing at that

**Comment by NightTsarina** [comment]
OH, I found something.. It actually **does not** exist, it just gives a 403 for every URL that does not pass the check!

```
POST http://wddcp.tincho.org/hq/admin/foo/
403 Forbidden
```

**Comment by lamby** [comment]
Sorry to repeat myself here, but I can't quite help but feel this is all already in my notes! ^ :)

**Comment by NightTsarina** [comment]
Sorry, yes, most of it is there, but evidently I had completely misunderstood them.  Please, note that this was me writing down things as I was seeing them.

Also, I was very confused by the notes when you say that " http://localhost:8000/hq/admin/session_details/ maps to corehq/apps/reports/dispatcher.py → AdminReportDispatcher." It actually does not, and that is why you get the 404, once the CSRF checks are removed.

**Comment by NightTsarina** [comment]
@DeckOfPandas:

> I think that's in my notes (?)

Yes, I see it now. But it was not in the production notes that I was following, which is quite a different procedure.

**Comment by NightTsarina** [comment]
Actually, I think the problem is very simple: the session_details endpoint was added in the dimagi repo after the wddcp branch. The formplayer repo is not synchronised with this and assumes dimagi's master.

I am now rebasing on top of master and rebuilding, I think this should make things work.

**Comment by NightTsarina** [comment]
Oh, joy. Now all this works, but the formplayer throws an error. Will look into this tomorrow.

```
2017-10-07 21:28:45.279 DEBUG 3563 --- [nio-8080-exec-1] o.s.web.servlet.DispatcherServlet        : Handler execution resulted in exception - forwarding to resolved error view: ModelAndView: reference to view with name 'error/error'; model is {exception=java.lang.ArrayIndexOutOfBoundsException: 0}

java.lang.ArrayIndexOutOfBoundsException: 0
        at aspects.LoggingAspect.logRequest(LoggingAspect.java:35) ~[classes!/:na]
```

**Comment by DeckOfPandas** [comment]
Wonderful, thank you! (And @lamby too)

**Comment by lamby** [comment]
Don't worry just glad we're making progress :) :)

**Comment by NightTsarina** [comment]
Oh, no, hold on.. that was an error while logging an error to write a file (permissions thing).. I have just filled my first form!!

Now I get another error: `Error setting user context. Ensure that raven is configured.` Something is missing, but I think this is almost ready to go! :-)

**Comment by NightTsarina** [comment]
Hey. So, I was silent for the last few days as I was moving countries.

I went today to test again to see what was the issue with this Raven thing, but whatever was going on (it was Saturday night, and I only tested briefly) it is solved now. I have submitted surveys with the simulator, syncronised data, etc. And no errors!

If you want to try it, I can give you credentials for my test server. I think this might be solved now. :-)

**Comment by bsharif** [comment]
Wow, super work! 

Would LOVE to test it please! ben.sharif@live.com

**Comment by NightTsarina** [comment]
Well, now to send you an invite I have to setup mail, which is refusing to work.. :)

Bear with me a little while till I figure this out. Also django logging refuses to cooperate.

**Comment by NightTsarina** [comment]
A-ha.. Email sending is done with a celery queue, and celery was not started.. This is a rabbit hole!

**Comment by rmlundin** [comment]
Fantastic! If you wouldn’t mind adding me as well, that would be great. Robert@wddcp.ac.uk - thanks and great work!

**Comment by DeckOfPandas** [comment]
Me too please!

And @Tincho, thank you so much (again)

**Comment by NightTsarina** [comment]
@bsharif I think I finally managed. Did you receive the invite?

**Comment by bsharif** [comment]
Email received - just registered and logged in successfully !

**Comment by bsharif** [comment]
Whoa...I'm in and it works! Super job! 
Made a new app, and a web user, and submitted some data. Formplayer preview works great too!

**Comment by NightTsarina** [comment]
I send the invitations, and resend the pending ones that @bsharif created. I am still not managing to make celery work properly, so I had to hack it. But please, test the rest and tell me how it goes for you.

Bear in mind that since I am changing stuff all the time, it will sometimes appear as down to you.

**Comment by rmlundin** [comment]
Thanks! They were all for me as the first two didn't go through (and ended up in @bsharif 's spam) I tried a few different providers. They have all showed up now in reverse order, so looks good.

**Comment by NightTsarina** [comment]
@DeckOfPandas Did you get yours?
