### ISSUE TITLE
Tincho's notes

### ISSUE THREAD

**Issue by NightTsarina** [WDDCP/commcare-wddcp#33]
I opened this issue just to paste links and maybe-useful things as I find them. Please ignore :-)

**Comment by NightTsarina** [comment]
Some possibly useful data from a kind of job posting: [Dimagi devops needs](https://docs.google.com/document/d/1tQFDC56SU8N1M-1abDWpnQKti2zYroTPBC2EmeIM8SA/pub)

**Comment by NightTsarina** [comment]
The submodules are out of sync, and can't be checked out. I had to run this locally (commcare being the dimagi/commcare remote):

```
$ git reset commcare/master .gitmodules submodules/ deployment/commcare-hq-deploy corehq/apps/prelogin corehq/apps/hqmedia/static/hqmedia/MediaUploader
$ git checkout commcare/master .gitmodules submodules/ deployment/commcare-hq-deploy corehq/apps/prelogin corehq/apps/hqmedia/static/hqmedia/MediaUploader
```

**Comment by NightTsarina** [comment]
When building formplayer, a different gradle version made an unusable jar: it was lacking dependencies and, most importantly, the needed metadata to execute in MANIFEST.MF

**Comment by NightTsarina** [comment]
When following the setup guide for HQ, it failed to start due to current kernels not supporting aufs any more, and there was a bug in the overlayfs support:

```
diff --git a/docker/run.sh b/docker/run.sh
index 3c5fb40..a812f4b 100755
--- a/docker/run.sh
+++ b/docker/run.sh
@@ -170,6 +170,7 @@ else
     if [ "$DOCKER_HQ_OVERLAY" == "overlayfs" ]; then
         rm -rf lib/work
         mkdir lib/work
+        chown cchq:cchq lib/overlay lib/staticfiles lib/work
         mount -t overlay -olowerdir=commcare-hq-ro,upperdir=lib/overlay,workdir=lib/work overlay commcare-hq
     else
         mount -t aufs -o br=lib/overlay:commcare-hq-ro none commcare-hq
```

**Comment by NightTsarina** [comment]
Then, I experienced a python failure when running the bootstrap, that was very difficult to debug due to docker being in the middle, plus all the custom scripts made it terribly slow.

```
Traceback (most recent call last):
  File "./manage.py", line 118, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 341, in execute
    django.setup()
  File "/usr/local/lib/python2.7/site-packages/django/__init__.py", line 22, in setup
    configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
  File "/usr/local/lib/python2.7/site-packages/django/utils/log.py", line 75, in configure_logging
    logging_config_func(logging_settings)
  File "/usr/local/lib/python2.7/logging/config.py", line 794, in dictConfig
    dictConfigClass(config).configure()
  File "/usr/local/lib/python2.7/logging/config.py", line 559, in configure
    'filter %r: %s' % (name, e))
ValueError: Unable to configure filter 'hqcontext': Cannot resolve 'corehq.util.log.HQRequestFilter': No module named dimagi.utils.chunked
```

**Comment by NightTsarina** [comment]
When trying the method described in `PRODUCTION-INSTALL.md`, `pip install` would fail due to filling the `/tmp` directory (which is a ramdisk). Passing the `-b ~/tmp` option solved this.

**Comment by NightTsarina** [comment]
Turns out, the python failure was due to backporting the submodules change from master, as it removes some of the needed libraries.. So I had to revert part of that commit

**Comment by NightTsarina** [comment]
FINALLY, I managed to get this thing working. It was way easier by not using docker.

Now to actually make the forms work..

**Comment by NightTsarina** [comment]
Issues I am still trying to solve:
* Making celery/celery beat work.
  * The issue with celery beat seems to be due to shitty coding (a chdir() into a work directoy making imports fail)
* Making pillowtops run, andmaybe understanding WTH are those.

**Comment by NightTsarina** [comment]
Celery beat now works. I had to use the full path to the manage script to avoid this issue. The problem that remains and that I was not able to fix so far, is why the tasks not started by beat are lost. The only solution I have found for now is to set `CELERY_ALWAYS_EAGER = True` so all the celery machinery is actually ignored.
